### ISSUE TITLE
How do you disable the dockerfile-maven plugin on a `mvn deploy`

### ISSUE THREAD

**Issue by pswenson** [spotify/dockerfile-maven#87] opened 2017-10-20 17:23 UTC
I want to separate out the docker build, pushes from the deploy goal.

I looked at the source and see this code: https://github.com/spotify/dockerfile-maven/blob/master/plugin/src/main/java/com/spotify/plugin/dockerfile/AbstractDockerMojo.java#L146

this code indicates I should be able to use a `-Ddockerfile.skip=true` to run deploy without the docker build/push.

`mvn -DskipTests -Ddockerfile.skip=true  deploy`

Unfortunately, it still builds and pushes to docker... 

Ideas?

**Comment by mattnworb** [comment] 2017-10-20 18:14
@pswenson could you post the part of your pom.xml where you include and configure the plugin?

I'm not able to reproduce this in a project that uses dockerfile-maven-plugin - if I invoke it like `mvn -Ddockerfile.skip deploy` then I see the following in the output:

```
[INFO] --- dockerfile-maven-plugin:1.3.2:build (default) @ hello-world ---
[INFO] Skipping execution because 'dockerfile.skip' is set

...

[INFO] --- dockerfile-maven-plugin:1.3.2:push (default) @ hello-gke-world ---
[INFO] Skipping execution because 'dockerfile.skip' is set
```

**Comment by derekbassett** [comment] 2017-10-20 18:33
Hey I work with @pswenson so maybe I can give some more context.
We have a multi-pom project which has a sub-project that wants to build a docker image.  
We want to be able to call `mvn dockerfile:build dockerfile:push` at the parent pom project and get it to build and push all docker images built in the child poms.  Here is the solution we came up with.

In the parent pom we put
```          
<plugin>
        <groupId>com.spotify</groupId>
        <artifactId>dockerfile-maven-plugin</artifactId>
        <version>1.3.6</version>
        <configuration>
            <skip>true</skip>
         </configuration>
</plugin>
``` 

In the child pom we put 
```
<plugin>
       <groupId>com.spotify</groupId>
       <artifactId>dockerfile-maven-plugin</artifactId>
       <configuration>
             <repository>${docker.registry}/${docker.image}</repository>
             <tag>${docker.tag}</tag>
             <buildArgs>
                 <JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
              </buildArgs>
              <skip>${dockerfile.skip}</skip>
        </configuration>
        <executions>
             <execution>
                 <id>default</id>
                 <goals>
                      <goal>build</goal>
                      <goal>push</goal>
                  </goals>
             </execution>
         </executions>
</plugin>
```

This allows us at the top level of the pom call `mvn dockerfile:build` to build all our children docker images, and at our top level `mvn dockerfile.skip=true deploy` will skip generating docker images in the deploy phase.

**Comment by mattnworb** [comment] 2017-10-20 18:39
Thanks for the extra context, but I'm not sure what the problem you are running into is anymore - does it not work as you desire for the child pom?

**Comment by derekbassett** [comment] 2017-10-20 19:48
So we are required to add ${dockerfile.skip} in the configuration section.  It looks like an ordering issue where <configuration><skip> in the plugin section is overriding the behavior of the property of dockerfile.skip.  That seems like a bug.

**Comment by mattnworb** [comment] 2017-10-20 20:35
This sounds to me like more of an issue with Maven and multimodule projects than an issue with the plugin specifically.

One approach I would suggest trying is to not specify anything for configuration/skip in the parent pom, and just set `<skip>true</skip>` in the child modules that you don't want to build docker images for. This way there is no property that you need to set, or no value that you need to override (the only overriding that is done is to override the default skip value of false with true in the modules that you want to skip.

I'd also suggest just binding the build/push goal in the parent pom, so that you only ever really need to do `mvn package` or `mvn deploy` and never need to do `mvn dockerfile:build` or any other goal from the CLI.

**Comment by mattnworb** [comment] 2017-10-20 20:39
>  It looks like an ordering issue where <configuration><skip> in the plugin section is overriding the behavior of the property of `dockerfile.skip`. That seems like a bug.

In case it is not clear, [the `<plugins>` section of the parent pom is inherited by each child pom](http://maven.apache.org/pom.html#Plugins), so I think the need to add a property in the child pom to override the parent pom's value stems from putting `<skip>true</skip>` in the parent pom.

**Comment by mattnworb** [comment] 2017-10-23 11:55
Another option I would suggest is to configure the plugin in each child pom and not the parent pom's `plugins` section (you might want to use `<pluginManagement>` to be able to control the version at least). You'll probably never want to package the parent pom as a docker image, so this means you won't need to set the parent and inherited configuration to skip=false.

I'm going to close this as it appear to be an issue with parent-child module relationships and a question of how best to set that up rather than an issue with dockerfile-maven-plugin.

**Closed by mattnworb** 2017-10-23 11:55 UTC

**Comment by segator** [comment] 2019-03-15 10:48
skip tag doesnt work Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:tag (default-cli) on project pm-dashboard-backend: The parameters 'repository' for goal com.spotify:dockerfile-maven-plugin:1.4.10:tag are missing or invalid -> [Help 1]
