### ISSUE TITLE
Using mave in the buildArgs parameter of configuration, can't get ${project.basedir} normally

### ISSUE THREAD

**Issue by ToQuery** [spotify/dockerfile-maven#209] opened 2018-08-29 01:21 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

## Description

Using mave in the buildArgs parameter of configuration, can't get ${project.basedir} normally.
Customize the dockerfile file address
The actual output is `/var/lib/docker/tmp/xxxxxxxxxxxx/${projextPath}/target`

eq:
``` xml
<plugin>
                    <groupId>com.spotify</groupId>
                    <artifactId>dockerfile-maven-plugin</artifactId>
                    <version>1.4.4</version>
                    <configuration>
             <repository>${docker.repository}/${docker.image.prefix}/${docker.image.name</repository> 
                        <contextDirectory>${project.basedir}/src/main/docker</contextDirectory>
                      <tag>${docker.image.tag}</tag>
                        <buildArgs>
                            <JAR_FILE>${project.basedir}/${docker.image.jar}</JAR_FILE>
                        </buildArgs>
                    </configuration>
</plugin>
```

## How to reproduce

As described above

## What do you expect

How to get the target path of the Maven project normally

## Software:
- mac os 10.13.6 
- `docker version`: 18.06.0-ce
- Spotify's dockerfile-maven version: 1.4.4

## Full backtrace

```text
No
```

**Comment by boskoop** [comment] 2018-10-16 17:13
I think this is a bug, as the plugin somehow modifies the Maven `${project.basedir}` variable.

I was using the following configuration in order to avoid hard-coding of the build-directory in the Dockerfile (normally ./target):
```
<buildArgs>
	<JAR_FILE>${project.build.directory}/${project.build.finalName}.jar</JAR_FILE>
	<PROJECT_NAME>${project.artifactId}</PROJECT_NAME>
	<PROJECT_VERSION>${project.version}</PROJECT_VERSION>
</buildArgs>
```

The variable `${project.build.directory}` points to the directory `/var/lib/docker/tmp/docker-builder<xxxxxxxxx>/${project.basedir}/target` instead of `${project.basedir}/target` when executing the `dockerfile:build` goal.

I think that the plugin modifies the `${project.basedir}` variable by prefixing the docker-builder temp directory.

**Comment by bbortt** [comment] 2018-10-17 05:10
I think it might be intentionally.. If you take a look at the current [README](https://github.com/spotify/dockerfile-maven/blob/master/README.md): They pass the jar-name like this:
```
<buildArgs>
      <JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
</buildArgs>
```
and kind of "configure" the target directory right in the Dockerfile with `ADD target/${JAR_FILE} /usr/share/myservice/myservice.jar`. Presuming the Dockerfile is located in your root directory, which is kind of standard.

Assuming you've changed your standard output directory, you missbehave to their very first design goal: 

> Don't do anything fancy.

Besides that I completely agree: It is a bit missleading and not very self explanatory.

**Comment by boskoop** [comment] 2018-10-17 12:07
The Maven variable `${project.build.directory}` is a standard variable, which should not be changed by the plugin. Using it in the POM is by no means fancy, imho it is best practice to use this variable to reference the build directory instead of hard-coding it with 'target'.

**Comment by mattnworb** [comment] 2018-10-17 12:17
I can’t recall any place in the plugin where this variable is modified - I’m not even sure if it is possible to modify a Maven supplied variable like that. Can anyone point to a piece of code that is doing this?

**Comment by mattnworb** [comment] 2018-10-17 12:18
One thing to note is that your local workspace is wrapped up and sent to the docker daemon as your “build context”

**Comment by boskoop** [comment] 2018-10-17 19:39
That probably is the explanation. But I do not understand why the following works:
```
<buildArgs>
	<JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
</buildArgs>
```
Dockerfile:
```
ARG JAR_FILE
ADD ${JAR_FILE} /usr/share/myservice/myservice.jar
`
``

While (as said before) the following does not work: 
```
<buildArgs>
	<JAR_FILE>${project.build.directory}/${project.build.finalName}.jar</JAR_FILE>
</buildArgs>
```
Dockerfile:
```
ARG JAR_FILE
ADD ${JAR_FILE} /usr/share/myservice/myservice.jar
```

I will try to investigate with a sample project.

**Comment by boskoop** [comment] 2018-10-17 20:49
So I created a sample project: https://github.com/boskoop/dockerfile-maven-issue-209

Actually, this issue seems to be a duplicate of https://github.com/spotify/dockerfile-maven/issues/101.

The problem is not with the Maven variable itself but with the design of the docker build context, where absolute paths are not allowed. The variable `${project.build.directory}` is an absolute path to the build directory.

Since more and more people are running into this (as I was too), we should think about improving the documentation.

**Comment by mattnworb** [comment] 2018-10-17 21:50
for a more complete explanation see #101

**Closed by mattnworb** 2018-10-17 21:50 UTC
